"""California county names"""


bay_area_counties = [
    "alameda",
    "contra_costa",
    "marin",
    "napa",
    "san_francisco",
    "san_mateo",
    "santa_clara",
    "sonoma",
    "solano"
]

other_ca_counties = [
    "amador",
    "butte",
    "calaveras",
    "colusa",
    "del_norte",
    "el_dorado",
    "fresno",
    "glenn",
    "humboldt",
    "imperial",
    "inyo",
    "kern",
    "kings",
    "lake",
    "lassen",
    "los_angeles",
    "madera",
    "mariposa",
    "mendocino",
    "merced",
    "modoc",
    "mono",
    "monterey",
    "nevada",
    "orange",
    "placer",
    "plumas",
    "riverside",
    "sacramento",
    "san_benito",
    "san_bernardino",
    "san_diego",
    "san_joaquin",
    "san_luis_obispo",
    "santa_barbara",
    "santa_cruz",
    "shasta",
    "siskiyou",
    "stanislaus",
    "sutter",
    "tehama",
    "trinity",
    "tulare",
    "tuolumne",
    "ventura",
    "yolo",
    "yuba"
]
